spi: qspi: cannot use pointer type in shift operand directly
drivers/spi/spi-dw-quad.c: In function 'set_cs':
./include/vdso/bits.h:7:40: error: invalid operands to binary << (have 'long unsigned int' and 'u8 *' {aka 'unsigned char *'})
    7 | #define BIT(nr)                 (UL(1) << (nr))
      |                                        ^~
      |                                        |
      |                                        u8 * {aka unsigned char *}
drivers/spi/spi-dw-quad.c:228:44: note: in expansion of macro 'BIT'
  228 |                 dw_writel(dws, DW_SPI_SER, BIT(spi->chip_select));
      |                                            ^~~

Fixes: 5d2672305852 ("drivers/spi: Add THEAD TH1520 QSPI driver")
Signed-off-by: Celeste Liu <CoelacanthusHex@gmail.com>