regulator: th1520: incompatible type assignment
drivers/firmware/xuantie/th1520_aon_pd.c: In function 'th1520_aon_init_pm_domains':
drivers/firmware/xuantie/th1520_aon_pd.c:213:24: error: assignment to 'genpd_xlate_t' {aka 'struct generic_pm_domain * (*)(const struct of_phandle_args *, void *)'} from incompatible pointer type 'struct generic_pm_domain * (*)(struct of_phandle_args *, void *)' [-Wincompatible-pointer-types]
  213 |         pd_data->xlate = th1520_aon_pd_xlate;
      |                        ^

Fixes: 6d3bbc942613 ("drivers: regulator: add th1520 AON virtual regulator control support.")
Signed-off-by: Celeste Liu <CoelacanthusHex@gmail.com>